version: '3'

services:
  postresql:
    image: postgres:16-alpine
    container_name: ${POSTGRES_DB}
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
    - ./data/postgres:/var/lib/postgresql/data

  # mongodb:
  #   image: mongo:7.0.8-nanoserver
  #   container_name: kardex_mongodb
  #   ports:
  #     - "${MONGODB_PORT:-27017}:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME:-admin}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD:-admin}
  #   volumes:
  #     - ./data/mongodb:/data/db
